// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SistemaTurnos.Dal.Data;

#nullable disable

namespace SistemaTurnos.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20240708192346_inicial")]
    partial class inicial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SistemaTurnos.Dal.Entities.DiaSemana", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("DiasSemana");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nombre = "Lunes"
                        },
                        new
                        {
                            Id = 2,
                            Nombre = "Martes"
                        },
                        new
                        {
                            Id = 3,
                            Nombre = "Miercoles"
                        },
                        new
                        {
                            Id = 4,
                            Nombre = "Jueves"
                        },
                        new
                        {
                            Id = 5,
                            Nombre = "Viernes"
                        },
                        new
                        {
                            Id = 6,
                            Nombre = "Sabado"
                        },
                        new
                        {
                            Id = 7,
                            Nombre = "Domingo"
                        });
                });

            modelBuilder.Entity("SistemaTurnos.Dal.Entities.DisponibilidadMedico", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DiaSemanaId")
                        .HasColumnType("int");

                    b.Property<TimeSpan>("EndTime")
                        .HasColumnType("time");

                    b.Property<int>("MedicoId")
                        .HasColumnType("int");

                    b.Property<TimeSpan>("StartTime")
                        .HasColumnType("time");

                    b.HasKey("Id");

                    b.HasIndex("DiaSemanaId");

                    b.HasIndex("MedicoId");

                    b.ToTable("DisponibilidadMedicos");
                });

            modelBuilder.Entity("SistemaTurnos.Dal.Entities.Especialidad", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Especialidades");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Descripcion = "Especialidad médica que se ocupa del estudio, diagnóstico y tratamiento de las enfermedades del corazón y del sistema circulatorio.",
                            Nombre = "Cardiología"
                        },
                        new
                        {
                            Id = 2,
                            Descripcion = "Especialidad médica que se encarga del estudio de la piel, su estructura, función y enfermedades.",
                            Nombre = "Dermatología"
                        },
                        new
                        {
                            Id = 3,
                            Descripcion = "Especialidad médica que se encarga del estudio, diagnóstico y tratamiento de las enfermedades del sistema nervioso.",
                            Nombre = "Neurología"
                        });
                });

            modelBuilder.Entity("SistemaTurnos.Dal.Entities.EstadoUsuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("EstadoUsuarios");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nombre = "Activo"
                        },
                        new
                        {
                            Id = 2,
                            Nombre = "Inactivo"
                        },
                        new
                        {
                            Id = 3,
                            Nombre = "Suspendido"
                        },
                        new
                        {
                            Id = 4,
                            Nombre = "Eliminado"
                        });
                });

            modelBuilder.Entity("SistemaTurnos.Dal.Entities.Persona", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EstadoUsuarioId")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaNacimiento")
                        .HasColumnType("date");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NumeroDocumento")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SexoId")
                        .HasColumnType("int");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("EstadoUsuarioId");

                    b.HasIndex("SexoId");

                    b.ToTable("Personas");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Persona");

                    b.UseTphMappingStrategy();

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Apellido = "Pérez",
                            Email = "juan.perez@example.com",
                            EstadoUsuarioId = 1,
                            FechaCreacion = new DateTime(2024, 7, 8, 16, 23, 46, 322, DateTimeKind.Local).AddTicks(3913),
                            FechaNacimiento = new DateTime(1985, 5, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombre = "Juan",
                            NumeroDocumento = "12345678",
                            SexoId = 1,
                            Telefono = "123456789"
                        },
                        new
                        {
                            Id = 2,
                            Apellido = "Gómez",
                            Email = "maria.gomez@example.com",
                            EstadoUsuarioId = 1,
                            FechaCreacion = new DateTime(2024, 7, 8, 16, 23, 46, 322, DateTimeKind.Local).AddTicks(3960),
                            FechaNacimiento = new DateTime(1990, 8, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombre = "María",
                            NumeroDocumento = "87654321",
                            SexoId = 2,
                            Telefono = "987654321"
                        });
                });

            modelBuilder.Entity("SistemaTurnos.Dal.Entities.Rol", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nombre = "Admin"
                        },
                        new
                        {
                            Id = 2,
                            Nombre = "Secretario"
                        });
                });

            modelBuilder.Entity("SistemaTurnos.Dal.Entities.Sexo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Sexos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nombre = "Hombre"
                        },
                        new
                        {
                            Id = 2,
                            Nombre = "Mujer"
                        },
                        new
                        {
                            Id = 3,
                            Nombre = "Otro"
                        });
                });

            modelBuilder.Entity("SistemaTurnos.Dal.Entities.Administrativo", b =>
                {
                    b.HasBaseType("SistemaTurnos.Dal.Entities.Persona");

                    b.Property<int>("RolId")
                        .HasColumnType("int");

                    b.HasIndex("RolId");

                    b.HasDiscriminator().HasValue("Administrativo");

                    b.HasData(
                        new
                        {
                            Id = 8,
                            Apellido = "Martínez",
                            Email = "laura.martinez@ejemplo.com",
                            EstadoUsuarioId = 1,
                            FechaCreacion = new DateTime(2024, 7, 8, 16, 23, 46, 322, DateTimeKind.Local).AddTicks(8768),
                            FechaNacimiento = new DateTime(1990, 6, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombre = "Laura",
                            NumeroDocumento = "DNI65432100",
                            SexoId = 2,
                            Telefono = "111222333",
                            RolId = 1
                        },
                        new
                        {
                            Id = 9,
                            Apellido = "Sánchez",
                            Email = "pedro.sanchez@ejemplo.com",
                            EstadoUsuarioId = 1,
                            FechaCreacion = new DateTime(2024, 7, 8, 16, 23, 46, 322, DateTimeKind.Local).AddTicks(8772),
                            FechaNacimiento = new DateTime(1982, 4, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombre = "Pedro",
                            NumeroDocumento = "DNI12345001",
                            SexoId = 1,
                            Telefono = "444555666",
                            RolId = 2
                        });
                });

            modelBuilder.Entity("SistemaTurnos.Dal.Entities.Medico", b =>
                {
                    b.HasBaseType("SistemaTurnos.Dal.Entities.Persona");

                    b.Property<int>("EspecialidadId")
                        .HasColumnType("int");

                    b.Property<string>("NumeroLicencia")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasIndex("EspecialidadId");

                    b.HasDiscriminator().HasValue("Medico");

                    b.HasData(
                        new
                        {
                            Id = 5,
                            Apellido = "Pérez",
                            Email = "juan.perez@ejemplo.com",
                            EstadoUsuarioId = 1,
                            FechaCreacion = new DateTime(2024, 7, 8, 16, 23, 46, 322, DateTimeKind.Local).AddTicks(8207),
                            FechaNacimiento = new DateTime(1980, 5, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombre = "Juan",
                            NumeroDocumento = "DNI12345678",
                            SexoId = 1,
                            Telefono = "123456789",
                            EspecialidadId = 1,
                            NumeroLicencia = "LIC1234"
                        },
                        new
                        {
                            Id = 6,
                            Apellido = "González",
                            Email = "maria.gonzalez@ejemplo.com",
                            EstadoUsuarioId = 1,
                            FechaCreacion = new DateTime(2024, 7, 8, 16, 23, 46, 322, DateTimeKind.Local).AddTicks(8210),
                            FechaNacimiento = new DateTime(1975, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombre = "María",
                            NumeroDocumento = "DNI87654321",
                            SexoId = 2,
                            Telefono = "987654321",
                            EspecialidadId = 2,
                            NumeroLicencia = "LIC5678"
                        },
                        new
                        {
                            Id = 7,
                            Apellido = "López",
                            Email = "carlos.lopez@ejemplo.com",
                            EstadoUsuarioId = 1,
                            FechaCreacion = new DateTime(2024, 7, 8, 16, 23, 46, 322, DateTimeKind.Local).AddTicks(8213),
                            FechaNacimiento = new DateTime(1985, 12, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombre = "Carlos",
                            NumeroDocumento = "DNI23456789",
                            SexoId = 1,
                            Telefono = "555123456",
                            EspecialidadId = 3,
                            NumeroLicencia = "LIC9101"
                        });
                });

            modelBuilder.Entity("SistemaTurnos.Dal.Entities.Paciente", b =>
                {
                    b.HasBaseType("SistemaTurnos.Dal.Entities.Persona");

                    b.Property<string>("NombreEmergencia")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TelefonoEmergencia")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("Paciente");

                    b.HasData(
                        new
                        {
                            Id = 3,
                            Apellido = "Pérez",
                            Email = "juan.perez@example.com",
                            EstadoUsuarioId = 1,
                            FechaCreacion = new DateTime(2024, 7, 8, 16, 23, 46, 322, DateTimeKind.Local).AddTicks(7879),
                            FechaNacimiento = new DateTime(1985, 5, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombre = "Juan",
                            NumeroDocumento = "45345678",
                            SexoId = 1,
                            Telefono = "123452389",
                            NombreEmergencia = "Ana Pérez",
                            TelefonoEmergencia = "1122334455"
                        },
                        new
                        {
                            Id = 4,
                            Apellido = "Gómez",
                            Email = "maria.gomez@example.com",
                            EstadoUsuarioId = 1,
                            FechaCreacion = new DateTime(2024, 7, 8, 16, 23, 46, 322, DateTimeKind.Local).AddTicks(7889),
                            FechaNacimiento = new DateTime(1990, 8, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombre = "María",
                            NumeroDocumento = "12345678",
                            SexoId = 2,
                            Telefono = "123456756",
                            NombreEmergencia = "Carlos Gómez",
                            TelefonoEmergencia = "2233445566"
                        });
                });

            modelBuilder.Entity("SistemaTurnos.Dal.Entities.DisponibilidadMedico", b =>
                {
                    b.HasOne("SistemaTurnos.Dal.Entities.DiaSemana", "DiaSemana")
                        .WithMany()
                        .HasForeignKey("DiaSemanaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SistemaTurnos.Dal.Entities.Medico", "Medico")
                        .WithMany()
                        .HasForeignKey("MedicoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DiaSemana");

                    b.Navigation("Medico");
                });

            modelBuilder.Entity("SistemaTurnos.Dal.Entities.Persona", b =>
                {
                    b.HasOne("SistemaTurnos.Dal.Entities.EstadoUsuario", "EstadoUsuario")
                        .WithMany()
                        .HasForeignKey("EstadoUsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SistemaTurnos.Dal.Entities.Sexo", "Sexo")
                        .WithMany()
                        .HasForeignKey("SexoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EstadoUsuario");

                    b.Navigation("Sexo");
                });

            modelBuilder.Entity("SistemaTurnos.Dal.Entities.Administrativo", b =>
                {
                    b.HasOne("SistemaTurnos.Dal.Entities.Rol", "Rol")
                        .WithMany()
                        .HasForeignKey("RolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("SistemaTurnos.Dal.Entities.Medico", b =>
                {
                    b.HasOne("SistemaTurnos.Dal.Entities.Especialidad", "Especialidad")
                        .WithMany()
                        .HasForeignKey("EspecialidadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Especialidad");
                });
#pragma warning restore 612, 618
        }
    }
}
